{% set version = "1.5.3" %}
{% set commit = "bf6e6c0" %}

package:
  name: rnasik
  version: {{ version }}
  #version: "1.5.2+{{ version }}"

source:
  git_rev: {{ version }}
  #git_rev: {{ commit }}
  git_url: https://github.com/MonashBioinformaticsPlatform/RNAsik-pipe

build:
  number: 0
  #string: "{{ commit }}_0"

requirements:
  run:
    - bigdatascript=v2.0rc10
    - star=2.6.0c
    - bwa=0.7.17
    - hisat2
    - samtools=1.8
    - subread=1.6.2
    - skewer=0.2.2
    - bedtools=2.25.0
    - picard=2.18.9
    - fastqc=0.11.7
    - je-suite
    - multiqc
    #- qualimap

      #test:
      #  commands:
      #    - STAR --version
      #- bwa |& grep Version
      #- samtools |& grep Version
      #- bedtools --version > $bedtools2Version"
      #- counts -v |& sed '/^\s*$/d' > $featureCountsVersion"
      #- fastqc --version > $fastqcVersion"
      #- picard SortSam |& grep Version > $sortSamVersion"
      #- picard ReorderSam |& grep Version > $reorderSamVersion"
      #- picard MarkDuplicates |& grep Version > $markDupsVersion"
      #- qualimap --help | grep -A 1 QualiMap > $qualimapVersion"
      #- multiqc --version > $multiqcVersion"
      #- python --version |& grep Python > $pythonVersion"

about:
  home: "https://monashbioinformaticsplatform.github.io/RNAsik-pipe"
  license: Apache 2.0
  summary: "Pipeline for processing RNAseq data"
